//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEC_PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int Class_Id { get; set; }
        public string Class_Grade { get; set; }
        public string Class_Major { get; set; }
    }
}
