//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEC_PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Student_Id { get; set; }
        public string Student_Name { get; set; }
        public string Student_Age { get; set; }
        public string Student_Email { get; set; }
        public string Student_Password { get; set; }
        public int Role_Id { get; set; }
        public string Grade { get; set; }
        public string Major { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
